baseurl = "https://blog.benny-li.de"
languageCode = "en-us"
title = "Benny Li"
#theme = "split"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Benny Li"

[params]

  # Metadata for search engines and social sharing
  author = "Benny Li"
  description = "Personal landing page of Benny Li"
  #shareImage = "images/social.jpg"
  twitterHandle = "BennyLindemann"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/bennyli-suit.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Blog"
        url = "https://blog.benny-li.de"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/BennyLindemann"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/BennyLi"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Xing"
        url = "https://www.xing.com/profile/Benjamin_Lindemann2"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
